// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ST10446806_PROG6212_POEPART1.Data;

#nullable disable

namespace ST10446806_PROG6212_POEPART1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251121210306_SeedLecturerProfiles")]
    partial class SeedLecturerProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ST10446806_PROG6212_POEPART1.Claim", b =>
                {
                    b.Property<int>("ClaimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimID"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Documents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LecturerID")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ClaimID");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("ST10446806_PROG6212_POEPART1.LecturerProfile", b =>
                {
                    b.Property<int>("LecturerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LecturerID"));

                    b.Property<string>("BankDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LecturerID");

                    b.ToTable("LecturerProfiles");

                    b.HasData(
                        new
                        {
                            LecturerID = 1,
                            BankDetails = "Bank A",
                            Email = "doe.eye@gmail.com",
                            FullName = "Doe Eye",
                            HourlyRate = 0m,
                            PhoneNumber = "1234567890",
                            UserID = 1
                        },
                        new
                        {
                            LecturerID = 2,
                            BankDetails = "Bank B",
                            Email = "john.smith@gmail.com",
                            FullName = "John Smith",
                            HourlyRate = 0m,
                            PhoneNumber = "0987654321",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("ST10446806_PROG6212_POEPART1.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            FullName = "Doe Eye",
                            Password = "1234",
                            Role = 0,
                            Username = "lecturer1"
                        },
                        new
                        {
                            UserID = 2,
                            FullName = "John Smith",
                            Password = "1234",
                            Role = 1,
                            Username = "coordinator1"
                        },
                        new
                        {
                            UserID = 3,
                            FullName = "Michael Jackson",
                            Password = "1234",
                            Role = 2,
                            Username = "manager1"
                        },
                        new
                        {
                            UserID = 4,
                            FullName = "Alice White",
                            Password = "1234",
                            Role = 0,
                            Username = "lecturer2"
                        },
                        new
                        {
                            UserID = 5,
                            FullName = "Miss Piggy",
                            Password = "1234",
                            Role = 1,
                            Username = "coordinator2"
                        },
                        new
                        {
                            UserID = 6,
                            FullName = "Linken Black",
                            Password = "1234",
                            Role = 2,
                            Username = "manager2"
                        },
                        new
                        {
                            UserID = 7,
                            FullName = "Emma HR",
                            Password = "1234",
                            Role = 3,
                            Username = "hr1"
                        },
                        new
                        {
                            UserID = 8,
                            FullName = "Kermit Frog",
                            Password = "1234",
                            Role = 3,
                            Username = "hr2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
